from typing import Any, Dict, Optional

WORDING : Dict[str, Any] =\
{
	'conda_not_activated': 'Conda 未激活',
	'python_not_supported': '不支持 Python 版本，请升级到 {version} 或更高版本',
	'curl_not_installed': 'cURL 未安装',
	'ffmpeg_not_installed': 'FFMpeg 未安装',
	'creating_temp': '正在创建临时资源',
	'extracting_frames': '正在以 {resolution} 的分辨率和 {fps} 帧/秒的帧率提取帧',
	'extracting_frames_succeed': '提取帧成功',
	'extracting_frames_failed': '提取帧失败',
	'analysing': '正在分析',
	'extracting': '正在提取',
	'streaming': '正在流式传输',
	'processing': '正在处理',
	'merging': '正在合并',
	'downloading': '正在下载',
	'temp_frames_not_found': '未找到临时帧',
	'copying_image': '正在以 {resolution} 的分辨率复制图像',
	'copying_image_succeed': '复制图像成功',
	'copying_image_failed': '复制图像失败',
	'finalizing_image': '正在以 {resolution} 的分辨率完成图像',
	'finalizing_image_succeed': '完成图像成功',
	'finalizing_image_skipped': '跳过完成图像',
	'merging_video': '正在以 {resolution} 的分辨率和 {fps} 帧/秒的帧率合并视频',
	'merging_video_succeed': '合并视频成功',
	'merging_video_failed': '合并视频失败',
	'skipping_audio': '正在跳过音频',
	'replacing_audio_succeed': '替换音频成功',
	'replacing_audio_skipped': '跳过替换音频',
	'restoring_audio_succeed': '恢复音频成功',
	'restoring_audio_skipped': '跳过恢复音频',
	'clearing_temp': '正在清除临时资源',
	'processing_stopped': '处理已停止',
	'processing_image_succeed': '在 {seconds} 秒内成功处理为图像',
	'processing_image_failed': '处理为图像失败',
	'processing_video_succeed': '在 {seconds} 秒内成功处理为视频',
	'processing_video_failed': '处理为视频失败',
	'choose_image_source': '选择源图像',
	'choose_audio_source': '选择源音频',
	'choose_video_target': '选择目标视频',
	'choose_image_or_video_target': '选择目标图像或视频',
	'specify_image_or_video_output': '在目录中指定输出图像或视频',
	'match_target_and_output_extension': '匹配目标和输出扩展名',
	'no_source_face_detected': '未检测到源人脸',
	'processor_not_loaded': '无法加载处理器 {processor}',
	'processor_not_implemented': '处理器 {processor} 未正确实现',
	'ui_layout_not_loaded': '无法加载 UI 布局 {ui_layout}',
	'ui_layout_not_implemented': 'UI 布局 {ui_layout} 未正确实现',
	'stream_not_loaded': '无法加载流 {stream_mode}',
	'stream_not_supported': '不支持流',
	'job_created': '已创建作业 {job_id}',
	'job_not_created': '未创建作业 {job_id}',
	'job_submitted': '已提交作业 {job_id}',
	'job_not_submitted': '未提交作业 {job_id}',
	'job_all_submitted': '已提交所有作业',
	'job_all_not_submitted': '未提交所有作业',
	'job_deleted': '已删除作业 {job_id}',
	'job_not_deleted': '未删除作业 {job_id}',
	'job_all_deleted': '已删除所有作业',
	'job_all_not_deleted': '未删除所有作业',
	'job_step_added': '已将步骤添加到作业 {job_id}',
	'job_step_not_added': '未将步骤添加到作业 {job_id}',
	'job_remix_step_added': '已从作业 {job_id} 中混合步骤 {step_index}',
	'job_remix_step_not_added': '未从作业 {job_id} 中混合步骤 {step_index}',
	'job_step_inserted': '已将步骤 {step_index} 插入到作业 {job_id}',
	'job_step_not_inserted': '未将步骤 {step_index} 插入到作业 {job_id}',
	'job_step_removed': '已从作业 {job_id} 中删除步骤 {step_index}',
	'job_step_not_removed': '未从作业 {job_id} 中删除步骤 {step_index}',
	'running_job': '正在运行排队的作业 {job_id}',
	'running_jobs': '正在运行所有排队的作业',
	'retrying_job': '正在重试失败的作业 {job_id}',
	'retrying_jobs': '正在重试所有失败的作业',
	'processing_job_succeed': '作业 {job_id} 处理成功',
	'processing_jobs_succeed': '所有作业处理成功',
	'processing_job_failed': '作业 {job_id} 处理失败',
	'processing_jobs_failed': '所有作业处理失败',
	'processing_step': '正在处理步骤 {step_current}/{step_total}',
	'validating_hash_succeed': '{hash_file_name} 的哈希验证成功',
	'validating_hash_failed': '{hash_file_name} 的哈希验证失败',
	'validating_source_succeed': '{source_file_name} 的源验证成功',
	'validating_source_failed': '{source_file_name} 的源验证失败',
	'deleting_corrupt_source': '正在删除 {source_file_name} 的损坏源',
	'time_ago_now': '刚才',
	'time_ago_minutes': '{minutes} 分钟前',
	'time_ago_hours': '{hours} 小时 {minutes} 分钟前',
	'time_ago_days': '{days} 天 {hours} 小时 {minutes} 分钟前',
	'point': '。',
	'comma': '，',
	'colon': '：',
	'question_mark': '？',
	'exclamation_mark': '！',
	'help':
	{
		# installer
		'install_dependency': '选择要安装的 {dependency} 的变体',
		'skip_conda': '跳过 conda 环境检查',
		# paths
		'config_path': '选择要覆盖默认值的配置文件',
		'temp_path': '指定临时资源的目录',
		'jobs_path': '指定存储作业的目录',
		'source_paths': '选择图像或音频路径',
		'target_path': '选择图像或视频路径',
		'output_path': '在目录中指定图像或视频',
		# patterns
		'source_pattern': '选择图像或音频模式',
		'target_pattern': '选择图像或视频模式',
		'output_pattern': '指定图像或视频模式',
		# face detector
		'face_detector_model': '选择负责人脸检测的模型',
		'face_detector_size': '指定提供给人脸检测器的帧大小',
		'face_detector_angles': '指定在检测人脸之前旋转帧的角度',
		'face_detector_score': '根据置信度分数筛选检测到的人脸',
		# face landmarker
		'face_landmarker_model': '选择负责人脸界标检测的模型',
		'face_landmarker_score': '根据置信度分数筛选检测到的人脸界标',
		# face selector
		'face_selector_mode': '使用基于参考的跟踪或简单匹配',
		'face_selector_order': '指定检测到的人脸的顺序',
		'face_selector_age_start': '根据起始年龄筛选检测到的人脸',
		'face_selector_age_end': '根据结束年龄筛选检测到的人脸',
		'face_selector_gender': '根据性别筛选检测到的人脸',
		'face_selector_race': '根据种族筛选检测到的人脸',
		'reference_face_position': '指定用于创建参考人脸的位置',
		'reference_face_distance': '指定参考人脸和目标人脸之间的相似度',
		'reference_frame_number': '指定用于创建参考人脸的帧',
		# face masker
		'face_occluder_model': '选择负责遮挡蒙版的模型',
		'face_parser_model': '选择负责区域蒙版的模型',
		'face_mask_types': '混合和匹配不同的人脸蒙版类型 (选择: {choices})',
		'face_mask_areas': '选择用于区域蒙版的项目 (选择: {choices})',
		'face_mask_regions': '选择用于区域蒙版的项目 (选择: {choices})',
		'face_mask_blur': '指定应用于框蒙版的模糊程度',
		'face_mask_padding': '将上、右、下和左填充应用于框蒙版',
		# frame extraction
		'trim_frame_start': '指定目标视频的起始帧',
		'trim_frame_end': '指定目标视频的结束帧',
		'temp_frame_format': '指定临时资源格式',
		'keep_temp': '处理后保留临时资源',
		# output creation
		'output_image_quality': '指定图像质量，该质量会转换为图像压缩',
		'output_image_resolution': '根据目标图像指定图像分辨率',
		'output_audio_encoder': '指定用于音频的编码器',
		'output_audio_quality': '指定音频质量，该质量会转换为音频压缩',
		'output_audio_volume': '根据目标视频指定音频音量',
		'output_video_encoder': '指定用于视频的编码器',
		'output_video_preset': '平衡快速视频处理和视频文件大小',
		'output_video_quality': '指定视频质量，该质量会转换为视频压缩',
		'output_video_resolution': '根据目标视频指定视频分辨率',
		'output_video_fps': '根据目标视频指定视频 fps',
		# processors
		'processors': '加载单个或多个处理器 (选择: {choices}, ...)',
		'age_modifier_model': '选择负责人脸老化的模型',
		'age_modifier_direction': '指定年龄应修改的方向',
		'deep_swapper_model': '选择负责人脸交换的模型',
		'deep_swapper_morph': '在源人脸和目标人脸之间变形',
		'expression_restorer_model': '选择负责恢复表情的模型',
		'expression_restorer_factor': '从目标人脸恢复表情的因子',
		'face_debugger_items': '加载单个或多个处理器 (选择: {choices})',
		'face_editor_model': '选择负责人脸编辑的模型',
		'face_editor_eyebrow_direction': '指定眉毛方向',
		'face_editor_eye_gaze_horizontal': '指定水平注视',
		'face_editor_eye_gaze_vertical': '指定垂直注视',
		'face_editor_eye_open_ratio': '指定眼睛睁开的比例',
		'face_editor_lip_open_ratio': '指定嘴唇张开的比例',
		'face_editor_mouth_grim': '指定嘴巴的严峻表情',
		'face_editor_mouth_pout': '指定嘴巴的撅嘴表情',
		'face_editor_mouth_purse': '指定嘴巴的收拢表情',
		'face_editor_mouth_smile': '指定嘴巴的微笑表情',
		'face_editor_mouth_position_horizontal': '指定水平嘴巴位置',
		'face_editor_mouth_position_vertical': '指定垂直嘴巴位置',
		'face_editor_head_pitch': '指定头部俯仰',
		'face_editor_head_yaw': '指定头部偏航',
		'face_editor_head_roll': '指定头部侧滚',
		'face_enhancer_model': '选择负责人脸增强的模型',
		'face_enhancer_blend': '将增强的人脸混合到先前的人脸中',
		'face_enhancer_weight': '指定应用于人脸的权重程度',
		'face_swapper_model': '选择负责人脸交换的模型',
		'face_swapper_pixel_boost': '选择人脸交换器的像素提升分辨率',
		'frame_colorizer_model': '选择负责帧着色的模型',
		'frame_colorizer_size': '指定提供给帧着色器的帧大小',
		'frame_colorizer_blend': '将着色的帧混合到先前的帧中',
		'frame_enhancer_model': '选择负责帧增强的模型',
		'frame_enhancer_blend': '将增强的帧混合到先前的帧中',
		'lip_syncer_model': '选择负责唇形同步的模型',
		'lip_syncer_weight': '指定应用于嘴唇的权重程度',
		# uis
		'open_browser': '程序准备就绪后打开浏览器',
		'ui_layouts': '启动单个或多个 UI 布局 (选择: {choices}, ...)',
		'ui_workflow': '选择 UI 工作流程',
		# download
		'download_providers': '使用不同的提供商下载 (选择: {choices}, ...)',
		'download_scope': '指定下载范围',
		# benchmark
		'benchmark_resolutions': '选择基准测试的分辨率 (选择: {choices}, ...)',
		'benchmark_cycle_count': '指定每个基准测试的周期数',
		# execution
		'execution_device_id': '指定用于处理的设备',
		'execution_providers': '使用不同的提供商进行推理 (选择: {choices}, ...)',
		'execution_thread_count': '指定处理时的并行线程数',
		'execution_queue_count': '指定每个线程正在处理的帧数',
		# memory
		'video_memory_strategy': '平衡快速处理和低 VRAM 使用率',
		'system_memory_limit': '限制处理时可以使用的可用 RAM',
		# misc
		'log_level': '调整终端中显示的消息严重性',
		'halt_on_error': '发生错误时停止程序',
		# run
		'run': '运行程序',
		'headless_run': '在无头模式下运行程序',
		'batch_run': '在批处理模式下运行程序',
		'force_download': '强制自动下载并退出',
		'benchmark': '对程序进行基准测试',
		# jobs
		'job_id': '指定作业 ID',
		'job_status': '指定作业状态',
		'step_index': '指定步骤索引',
		# job manager
		'job_list': '按状态列出作业',
		'job_create': '创建草稿作业',
		'job_submit': '提交草稿作业以成为排队作业',
		'job_submit_all': '提交所有草稿作业以成为排队作业',
		'job_delete': '删除草稿、排队、失败或已完成的作业',
		'job_delete_all': '删除所有草稿、排队、失败和已完成的作业',
		'job_add_step': '向草稿作业添加步骤',
		'job_remix_step': '从草稿作业中混合先前的步骤',
		'job_insert_step': '向草稿作业插入步骤',
		'job_remove_step': '从草稿作业中删除步骤',
		# job runner
		'job_run': '运行排队的作业',
		'job_run_all': '运行所有排队的作业',
		'job_retry': '重试失败的作业',
		'job_retry_all': '重试所有失败的作业'
	},
	'about':
	{
		'become_a_member': '成为会员',
		'join_our_community': '加入我们的社区',
		'read_the_documentation': '阅读文档'
	},
	'uis':
	{
		'age_modifier_direction_slider': '年龄修改器方向',
		'age_modifier_model_dropdown': '年龄修改器模型',
		'apply_button': '应用',
		'benchmark_cycle_count_slider': '基准测试周期计数',
		'benchmark_resolutions_checkbox_group': '基准测试分辨率',
		'clear_button': '清除',
		'common_options_checkbox_group': '选项',
		'download_providers_checkbox_group': '下载提供商',
		'deep_swapper_model_dropdown': '深度交换器模型',
		'deep_swapper_morph_slider': '深度交换器变形',
		'execution_providers_checkbox_group': '执行提供商',
		'execution_queue_count_slider': '执行队列计数',
		'execution_thread_count_slider': '执行线程计数',
		'expression_restorer_factor_slider': '表情恢复因子',
		'expression_restorer_model_dropdown': '表情恢复模型',
		'face_debugger_items_checkbox_group': '人脸调试器项目',
		'face_detector_angles_checkbox_group': '人脸检测器角度',
		'face_detector_model_dropdown': '人脸检测器模型',
		'face_detector_score_slider': '人脸检测器分数',
		'face_detector_size_dropdown': '人脸检测器大小',
		'face_editor_eyebrow_direction_slider': '人脸编辑器眉毛方向',
		'face_editor_eye_gaze_horizontal_slider': '人脸编辑器水平注视',
		'face_editor_eye_gaze_vertical_slider': '人脸编辑器垂直注视',
		'face_editor_eye_open_ratio_slider': '人脸编辑器眼睛睁开比例',
		'face_editor_head_pitch_slider': '人脸编辑器头部俯仰',
		'face_editor_head_roll_slider': '人脸编辑器头部侧滚',
		'face_editor_head_yaw_slider': '人脸编辑器头部偏航',
		'face_editor_lip_open_ratio_slider': '人脸编辑器嘴唇张开比例',
		'face_editor_model_dropdown': '人脸编辑器模型',
		'face_editor_mouth_grim_slider': '人脸编辑器嘴巴严峻表情',
		'face_editor_mouth_position_horizontal_slider': '人脸编辑器水平嘴巴位置',
		'face_editor_mouth_position_vertical_slider': '人脸编辑器垂直嘴巴位置',
		'face_editor_mouth_pout_slider': '人脸编辑器嘴巴撅嘴表情',
		'face_editor_mouth_purse_slider': '人脸编辑器嘴巴收拢表情',
		'face_editor_mouth_smile_slider': '人脸编辑器嘴巴微笑表情',
		'face_enhancer_blend_slider': '人脸增强器混合',
		'face_enhancer_model_dropdown': '人脸增强器模型',
		'face_enhancer_weight_slider': '人脸增强器权重',
		'face_landmarker_model_dropdown': '人脸界标器模型',
		'face_landmarker_score_slider': '人脸界标器分数',
		'face_mask_blur_slider': '人脸蒙版模糊',
		'face_mask_padding_bottom_slider': '人脸蒙版下边距',
		'face_mask_padding_left_slider': '人脸蒙版左边距',
		'face_mask_padding_right_slider': '人脸蒙版右边距',
		'face_mask_padding_top_slider': '人脸蒙版上边距',
		'face_mask_areas_checkbox_group': '人脸蒙版区域',
		'face_mask_regions_checkbox_group': '人脸蒙版区域',
		'face_mask_types_checkbox_group': '人脸蒙版类型',
		'face_selector_age_range_slider': '人脸选择器年龄',
		'face_selector_gender_dropdown': '人脸选择器性别',
		'face_selector_mode_dropdown': '人脸选择器模式',
		'face_selector_order_dropdown': '人脸选择器顺序',
		'face_selector_race_dropdown': '人脸选择器种族',
		'face_swapper_model_dropdown': '人脸交换器模型',
		'face_swapper_pixel_boost_dropdown': '人脸交换器像素提升',
		'face_occluder_model_dropdown': '人脸遮挡器模型',
		'face_parser_model_dropdown': '人脸解析器模型',
		'frame_colorizer_blend_slider': '帧着色器混合',
		'frame_colorizer_model_dropdown': '帧着色器模型',
		'frame_colorizer_size_dropdown': '帧着色器大小',
		'frame_enhancer_blend_slider': '帧增强器混合',
		'frame_enhancer_model_dropdown': '帧增强器模型',
		'job_list_status_checkbox_group': '作业状态',
		'job_manager_job_action_dropdown': '作业操作',
		'job_manager_job_id_dropdown': '作业 ID',
		'job_manager_step_index_dropdown': '步骤索引',
		'job_runner_job_action_dropdown': '作业操作',
		'job_runner_job_id_dropdown': '作业 ID',
		'lip_syncer_model_dropdown': '唇形同步器模型',
		'lip_syncer_weight_slider': '唇形同步器权重',
		'log_level_dropdown': '日志级别',
		'output_audio_encoder_dropdown': '输出音频编码器',
		'output_audio_quality_slider': '输出音频质量',
		'output_audio_volume_slider': '输出音频音量',
		'output_image_or_video': '输出',
		'output_image_quality_slider': '输出图像质量',
		'output_image_resolution_dropdown': '输出图像分辨率',
		'output_path_textbox': '输出路径',
		'output_video_encoder_dropdown': '输出视频编码器',
		'output_video_fps_slider': '输出视频 FPS',
		'output_video_preset_dropdown': '输出视频预设',
		'output_video_quality_slider': '输出视频质量',
		'output_video_resolution_dropdown': '输出视频分辨率',
		'preview_frame_slider': '预览帧',
		'preview_image': '预览',
		'processors_checkbox_group': '处理器',
		'reference_face_distance_slider': '参考人脸距离',
		'reference_face_gallery': '参考人脸',
		'refresh_button': '刷新',
		'source_file': '源',
		'start_button': '开始',
		'stop_button': '停止',
		'system_memory_limit_slider': '系统内存限制',
		'target_file': '目标',
		'temp_frame_format_dropdown': '临时帧格式',
		'terminal_textbox': '终端',
		'trim_frame_slider': '修剪帧',
		'ui_workflow': 'UI 工作流程',
		'video_memory_strategy_dropdown': '视频内存策略',
		'webcam_fps_slider': '网络摄像头 FPS',
		'webcam_image': '网络摄像头',
		'webcam_device_id_dropdown': '网络摄像头设备 ID',
		'webcam_mode_radio': '网络摄像头模式',
		'webcam_resolution_dropdown': '网络摄像头分辨率'
	}
}


def get(notation : str) -> Optional[str]:
	current = WORDING

	for fragment in notation.split('.'):
		if fragment in current:
			current = current.get(fragment)
			if isinstance(current, str):
				return current

	return None